spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 862400486934-s9nsn72mcpqj8mqlupvvad36j15bqd0s.apps.googleusercontent.com
            clientSecret: z_hRpUrPSHqZuB4CVTa4ODOl
            scope:
              - openid
              - email
              - profile
          facebook:
            clientId: 298539834471115
            clientSecret: a388174d78514ba7cb9114d8a8319bb4
            scope:
              - email
              - public_profile
              - password
